version: "3"

services:
  app:
    image: ambientum/php:8.1-nginx
    container_name: cake-ignition-app
    volumes:
      - .:/var/www/app
      - ./nginx/sites:/etc/nginx/sites
      - ./scripts:/scripts/entry.d
    ports:
      - 80:8080
      - 443:8083
    networks:
      - cake-ignition
    environment:
      - FRAMEWORK=cake
      
  db:
    image: mysql
    container_name: cake-ignition-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: cakeignitiondb
    networks:
      - cake-ignition

networks:
  cake-ignition: